### ISSUE TITLE
renaming `Parser.Mermaid`

### ISSUE THREAD

**Issue by egidijusz** [am-kantox/finitomata#26]
Related to #25 

Maybe it would be worth it to rename `Parser.Mermaid` to `Parser.Flowchart` or `Parser.MermaidFlowchart` or something like that?

I could go ahead and do it if you're okay with this.

**Comment by am-kantox** [comment]
Hi @egidijusz, thanks for having your hands dirty with this, I appreciate it.

I am strongly against _renaming_ because it breaks backward compatibility. But in general, you are absolutely right. So I’d go with allowing regular atoms in `use Finitomata` clause for predefined syntaxes instead.

That said, we allow `:"Elixir.Foo.Bar.Baz"` atoms for _custom_ syntaxes, or deprecated `Finitomata.{Mermaid, PlantUML}`, or `:state_diagram` and/or `:flowchart` for predefined ones. Also, we clean up the documentation, getting rid of any mention of deprecated `Finitomata.{Mermaid, PlantUML}`.

If it sounds OK, the PR would be strongly appreciated.

**Comment by egidijusz** [comment]
Yes, that sounds very good. I'll give it a try in coming days.

I'll keep this Issue open, so I can attach the PR to it.
