### ISSUE TITLE
Capturing errors, e.g. forbidden transitions

### ISSUE THREAD

**Issue by peaceful-james** [am-kantox/finitomata#75]
When using this library, I have found that there is no ability to capture certain errors.

There is an `on_failure` callback but this callback only knows the event and the state. It does not know the actual error.

For example, when a particular transition is not allowed, we get a warning-level log message:

````
                Logger.warning("[⚐ ↹] transition failed " <> inspect(err))
````

But that `err` is then lost. In fact, this `err` does not seem to be accessible in any way!

I think this is of critical importance if this library is to be truly useful. FSM-logic errors need to be capturable.

**Comment by am-kantox** [comment]
Hi @peaceful-james, sorry for the not instant response,

There is an optional callback in the module that calls `use Finitomata`, [`on_failure/3`](https://hexdocs.pm/finitomata/Finitomata.html#c:on_failure/3), allowing to handle everything.

**Comment by peaceful-james** [comment]
Hi @am-kantox 

Sorry also for late response

![image](https://github.com/am-kantox/finitomata/assets/66864163/b636ea8e-3c6f-46e7-929b-1b78bd23cf88)

This image shows current code. `err` is not passed to `safe_on_failure`. This `err` is what is lost. I think this `err` would be useful for presenting to users.

**Comment by am-kantox** [comment]
Hi @peaceful-james,

two kinds of issues might happen with an _FSM_ implementation: the developer’s failure and the violation of the business logic. The latter is perfectly accessible from `on_failure/3` via `state.last_error` (set in the line 1011.)

The former, though, has nothing to do with the FSM itself and should be simply fixed in the code. Hence there is no trace of it in the state, only in logs. That’s basically why we have different `else` clauses to catch.
